name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: git clone https://github.com/Yelp/detect-secrets
      - name: second one
        run: |
        pip install detect-secrets
        detect-secrets
